# definitions.py — Offline word definitions dictionary
# Used by app_gui.py to show tooltips on suggestion hover.

DEFINITIONS = {
    "ability": "the power or skill to do something",
    "about": "on the subject of; concerning",
    "above": "at a higher level or position than",
    "absence": "the state of being away from a place",
    "abstract": "existing in thought or as an idea but not having physical existence",
    "accept": "to agree to take something offered",
    "access": "the right or ability to enter, use, or reach something",
    "accident": "an unfortunate event that happens unexpectedly",
    "account": "a record or description of events; a banking arrangement",
    "achieve": "to successfully bring about a desired result",
    "action": "the process of doing something to achieve an aim",
    "actually": "as a matter of fact; in reality",
    "add": "to put something with another thing to increase the number or amount",
    "address": "the location of a place; to speak to someone formally",
    "affect": "to have an effect on; make a difference to",
    "after": "following in time, place, or order",
    "again": "another time; once more",
    "age": "the length of time that a person or thing has existed",
    "ago": "before the present time",
    "agree": "to have the same opinion; to accept a suggestion",
    "ahead": "further forward in space or time",
    "allow": "to let someone do something; to permit",
    "already": "before or by now or the time in question",
    "also": "in addition; too",
    "always": "at all times; on all occasions",
    "among": "situated in the middle of; surrounded by",
    "answer": "a response to a question or problem",
    "apply": "to make a formal request; to put something into operation",
    "argue": "to give reasons for or against something; to disagree",
    "around": "on every side of; approximately",
    "arrive": "to reach a destination after traveling",
    "ask": "to say something in order to get information or a response",
    "attempt": "to make an effort to achieve something",
    "attention": "notice taken of someone or something; mental concentration",
    "attitude": "a settled way of thinking or feeling about something",
    "avoid": "to keep away from or stop oneself from doing something",
    "aware": "having knowledge or perception of a situation or fact",
    "away": "to or at a distance from a place",
    "back": "the rear side; to return to a previous position",
    "bad": "of poor quality; not good",
    "ball": "a round object used in games; a formal dance event",
    "basic": "forming an essential foundation; fundamental",
    "battle": "a fight between armed forces; a lengthy struggle",
    "beautiful": "pleasing the senses or mind aesthetically",
    "become": "to begin to be; to grow to be",
    "before": "during the period of time preceding a particular event",
    "begin": "to start; to perform the first part of an action",
    "believe": "to accept something as true or real",
    "better": "more desirable, satisfactory, or effective",
    "between": "in the space separating two things",
    "beyond": "at or to the far side of; more than",
    "big": "of considerable size or extent",
    "black": "the darkest color; the absence of light",
    "blue": "the color of a clear sky",
    "book": "a written or printed work consisting of pages",
    "both": "the two; referring to two people or things together",
    "break": "to separate into pieces; to fail to observe a rule",
    "bring": "to carry or take to a place",
    "build": "to construct by putting parts together",
    "busy": "having a great deal to do; occupied",
    "buy": "to obtain in exchange for payment",
    "call": "to give a name to; to make a phone call",
    "came": "past tense of come; to move toward",
    "can": "be able to; have the ability",
    "care": "the provision of what is needed; to feel concern",
    "carry": "to hold and transport from one place to another",
    "cause": "a person or thing that produces an effect; to make happen",
    "certain": "known for sure; without doubt",
    "change": "to make or become different",
    "charge": "a price asked for goods or services; to rush forward",
    "check": "to examine to verify; a written order to a bank",
    "choose": "to pick out or select as being the best",
    "city": "a large and important town",
    "claim": "to state or assert that something is the case",
    "clear": "easy to perceive or understand; to remove",
    "close": "at a short distance; to move to cover an opening",
    "cold": "of or at a low temperature",
    "color": "the property of producing different sensations on the eye",
    "come": "to move toward or into a place",
    "common": "occurring, found, or done often; widespread",
    "compare": "to estimate or note the similarity or difference between",
    "complete": "having all necessary parts; to finish making or doing",
    "concern": "worry; to be relevant or important to",
    "condition": "the circumstances affecting a person or thing",
    "consider": "to think carefully about; to regard as",
    "contain": "to have or hold within itself",
    "continue": "to persist in an activity or process",
    "control": "the power to influence or direct behavior",
    "correct": "free from error; right; to put right",
    "could": "past tense of can; used to indicate possibility",
    "count": "to determine the total number of; to be relevant",
    "country": "a nation with its own government",
    "course": "the route along which something moves; a series of lessons",
    "cover": "to put something over in order to protect or conceal",
    "create": "to bring something into existence",
    "cut": "to make an opening with a sharp tool; to reduce",
    "dark": "with little or no light present",
    "data": "facts and statistics collected for reference or analysis",
    "deal": "an agreement or arrangement; to distribute",
    "deep": "extending far down from the surface",
    "define": "to state or describe the exact nature or meaning of",
    "describe": "to give a detailed account of",
    "design": "to plan and create with a specific purpose",
    "develop": "to grow or cause to grow; to create over time",
    "different": "not the same as another; unlike",
    "difficult": "needing much effort or skill to do",
    "direction": "a course along which someone or something moves",
    "discover": "to find or learn something for the first time",
    "discuss": "to talk about a topic with others",
    "done": "carried out or completed",
    "doubt": "a feeling of uncertainty or lack of conviction",
    "down": "toward or in a lower place or position",
    "draw": "to produce a picture using a pencil or pen",
    "drive": "to operate and control a vehicle",
    "drop": "to let something fall; a small round portion of liquid",
    "during": "throughout the course or duration of",
    "each": "every one of two or more people or things",
    "early": "happening before the expected time",
    "earth": "the planet we live on; the soil or ground",
    "easy": "achieved without great effort; not difficult",
    "effect": "a change that is a result or consequence of an action",
    "effort": "a vigorous or determined attempt",
    "either": "each of two; used before the first of two options",
    "else": "in addition; different or instead",
    "empty": "containing nothing; not occupied",
    "end": "the final point of something; to come to a conclusion",
    "energy": "the strength and vitality required for activity",
    "enough": "as much or as many as required",
    "enter": "to go or come into a place",
    "environment": "the surroundings in which a person lives or operates",
    "equal": "the same in quantity, size, degree, or value",
    "error": "a mistake; something incorrect",
    "even": "flat and smooth; used to emphasize something unexpected",
    "event": "a thing that happens; an organized occasion",
    "ever": "at any time",
    "every": "each one of a group without exception",
    "example": "a thing representative of its kind; a specimen",
    "expect": "to regard as likely to happen",
    "experience": "practical knowledge gained through involvement",
    "explain": "to make clear by describing in more detail",
    "eye": "the organ of sight",
    "face": "the front part of the head; to confront",
    "fact": "a thing that is known to be true",
    "fail": "to be unsuccessful in achieving a goal",
    "fall": "to move downward; to decrease",
    "fast": "moving or capable of moving at high speed",
    "feel": "to be aware of through senses or emotions",
    "field": "an area of open land; a subject of study",
    "fight": "to engage in combat or conflict",
    "figure": "a number or symbol; to think or calculate",
    "fill": "to make full; to put a substance into a container",
    "final": "coming at the end; last",
    "find": "to discover or locate something",
    "finish": "to bring to an end; to complete",
    "first": "coming before all others in time or order",
    "five": "the number equivalent to the sum of two and three",
    "follow": "to go or come after; to obey",
    "force": "strength or energy exerted; to compel",
    "forget": "to fail to remember",
    "form": "the visible shape of something; to make or create",
    "forward": "toward the front; making progress",
    "found": "past tense of find; to establish an organization",
    "free": "not under the control of another; at no cost",
    "friend": "a person with whom you have a bond of mutual affection",
    "from": "indicating the point of origin",
    "front": "the side facing forward or toward the observer",
    "full": "containing as much as possible; complete",
    "general": "affecting or relating to all; a senior military officer",
    "give": "to freely transfer something to someone",
    "go": "to move from one place to another",
    "good": "to be desired or approved of; beneficial",
    "government": "the group of people with authority to govern a country",
    "great": "of an extent or intensity much above normal",
    "group": "a number of people or things together",
    "grow": "to increase in size or importance over time",
    "guess": "to estimate without definite knowledge",
    "happen": "to take place; to occur",
    "happy": "feeling or showing pleasure or contentment",
    "hard": "solid, firm, and rigid; requiring effort",
    "have": "to possess or own",
    "health": "the state of being free from illness",
    "heart": "the organ that pumps blood; feelings and emotions",
    "help": "to make it easier for someone to do something",
    "here": "in, at, or to this place",
    "high": "of great vertical extent; elevated",
    "history": "the study of past events",
    "hold": "to keep or detain; to grasp",
    "home": "the place where one lives",
    "hope": "a feeling of expectation for something good",
    "hour": "a period of sixty minutes",
    "house": "a building for human habitation",
    "human": "relating to people; a person",
    "hundred": "the number equivalent to ten times ten",
    "idea": "a thought or suggestion about a course of action",
    "identify": "to establish who or what someone or something is",
    "imagine": "to form a mental image of something",
    "impact": "the effect or influence of something",
    "improve": "to make or become better",
    "include": "to comprise as part of a whole",
    "increase": "to become or make greater in size or amount",
    "information": "facts provided or learned about something",
    "interest": "the feeling of wanting to know about something",
    "into": "expressing movement or direction to a point inside",
    "involve": "to include or affect someone in an activity",
    "issue": "an important topic for debate; to supply or distribute",
    "item": "an individual article or unit",
    "job": "a paid position of regular employment",
    "join": "to link or connect together",
    "just": "exactly; very recently; fair and reasonable",
    "keep": "to have or retain something; to continue",
    "kind": "a type or variety; generous and considerate",
    "know": "to be aware of through observation or experience",
    "knowledge": "facts, information, and skills acquired through experience",
    "land": "the earth's surface; to come down from the air",
    "large": "of considerable or relatively great size",
    "last": "coming after all others; most recent",
    "late": "doing something after the expected time",
    "lead": "to guide or direct; a soft heavy grey metal",
    "learn": "to gain knowledge or skill through study",
    "leave": "to go away from; to allow to remain",
    "left": "on or toward the west side; past tense of leave",
    "less": "a smaller amount of; to a smaller extent",
    "level": "a horizontal line or surface; a degree or intensity",
    "life": "the condition that distinguishes living organisms",
    "light": "natural or artificial illumination; not heavy",
    "like": "similar to; to find pleasant or attractive",
    "likely": "probable; probably",
    "line": "a long narrow mark; a row of people or things",
    "list": "a sequence of names or items",
    "live": "to be alive; existing at the present time",
    "long": "measuring a great distance; for a long time",
    "look": "to direct your eyes toward something",
    "lose": "to be deprived of; to fail to win",
    "love": "an intense feeling of deep affection",
    "low": "situated not far above the ground; below average",
    "main": "chief in importance or extent; principal",
    "make": "to form by putting parts together; to create",
    "manage": "to be in charge of; to succeed in doing",
    "many": "a large number of",
    "market": "a place where goods are bought and sold",
    "matter": "physical substance; to be important",
    "mean": "intend to convey; unkind; the average value",
    "measure": "to determine the size or amount of something",
    "meet": "to come into contact with; to satisfy a need",
    "method": "a particular way of doing something",
    "mind": "the element of intellect and consciousness",
    "miss": "to fail to hit or reach; to feel the absence of",
    "model": "a representation of something; a person who poses",
    "moment": "a very brief period of time",
    "money": "a medium of exchange in the form of coins or notes",
    "month": "a period of time approximately equal to four weeks",
    "more": "a greater or additional amount",
    "most": "greatest in amount or degree",
    "move": "to go in a specified direction; to change position",
    "much": "a great amount or degree",
    "must": "be obliged to; used to express necessity",
    "name": "a word by which a person or thing is known",
    "nation": "a large body of people united by common history",
    "nature": "the physical world including plants and animals",
    "need": "require something because it is essential",
    "never": "at no time; not ever",
    "next": "coming immediately after; the one nearest",
    "night": "the period of darkness in each twenty-four hours",
    "none": "not any; no person",
    "north": "the direction toward the pole on the left of sunrise",
    "note": "a brief written record; a short comment",
    "nothing": "not anything; no single thing",
    "notice": "to become aware of; a formal announcement",
    "now": "at the present time",
    "number": "an arithmetical value; to count",
    "object": "a material thing; to express disagreement",
    "often": "frequently; many times",
    "once": "one time; as soon as",
    "open": "not closed or blocked; to allow access",
    "order": "an arrangement; an instruction; to request something",
    "other": "different from the one mentioned; additional",
    "outside": "the external side; beyond the limits of",
    "over": "extending above; more than",
    "own": "belonging to oneself; to possess",
    "paper": "material manufactured from pulp; a newspaper",
    "part": "a piece or segment of something",
    "pass": "to move past; to succeed in a test",
    "past": "gone by in time; the time before the present",
    "pay": "to give money owed for goods or services",
    "people": "human beings in general",
    "perhaps": "used to express uncertainty; possibly",
    "person": "a human being regarded as an individual",
    "place": "a particular position or point in space",
    "plan": "an intention for achieving something; to decide",
    "play": "to engage in activity for enjoyment",
    "point": "the tapered end of something; a particular detail",
    "possible": "able to happen or be done",
    "power": "the ability to do something; energy or strength",
    "practice": "repeated exercise to improve a skill; usual behavior",
    "prepare": "to make ready for use or consideration",
    "present": "being in a place; a gift; the current time",
    "prevent": "to keep from happening",
    "problem": "a matter that is difficult to deal with",
    "produce": "to make or create; to show or provide",
    "program": "a planned series of events; a set of instructions for a computer",
    "prove": "to demonstrate the truth of something",
    "provide": "to make available for use; to supply",
    "public": "of or concerning all the people; open to everyone",
    "pull": "to exert force to move something toward oneself",
    "push": "to exert force to move something away",
    "question": "a sentence that asks for information",
    "quick": "moving fast; done with speed",
    "quite": "to a certain degree; completely",
    "raise": "to lift up; to increase the amount of",
    "reach": "to stretch out to touch or get something",
    "read": "to look at and understand written material",
    "ready": "prepared; willing and able to do",
    "real": "actually existing; not imaginary",
    "reason": "a cause or explanation for something",
    "receive": "to be given or presented with something",
    "reduce": "to make smaller or less in amount",
    "remain": "to continue to exist; to stay in the same place",
    "remember": "to have in or bring to mind again",
    "remove": "to take away or eliminate",
    "report": "an account giving information about something",
    "require": "to need something; to make something necessary",
    "result": "a consequence or outcome of something",
    "return": "to come or go back to a place",
    "right": "morally good; the right-hand side; correct",
    "rise": "to move upward; to get up from lying down",
    "road": "a wide way for vehicles to travel on",
    "room": "a space in a building enclosed by walls",
    "rule": "a principle that governs conduct; to exercise control",
    "run": "to move at a speed faster than walking",
    "safe": "protected from harm; not dangerous",
    "same": "identical; not different",
    "save": "to keep safe from harm; to keep for future use",
    "say": "to utter words; to express in words",
    "school": "an institution for educating children",
    "seek": "to attempt to find or obtain",
    "seem": "to give the impression of being",
    "send": "to cause to go to a destination",
    "sense": "a faculty by which the body perceives; meaning",
    "serve": "to perform services for; to be useful to",
    "set": "to put, lay, or stand in a position; a group of things",
    "share": "to divide and distribute in portions; a part owned",
    "short": "measuring a small distance from end to end",
    "show": "to make visible or known; a performance",
    "sign": "an indication of something; to write one's name",
    "simple": "easily understood or done; not complex",
    "since": "from a specified time in the past; because",
    "size": "the overall dimensions or extent of something",
    "skill": "the ability to do something well through practice",
    "slow": "moving or operating at a low speed",
    "small": "of a size that is less than normal",
    "solve": "to find a solution to a problem",
    "some": "an unspecified amount or number of",
    "soon": "in or after a short time",
    "sort": "a category of things; to arrange systematically",
    "sound": "vibrations that travel through the air as noise",
    "south": "the direction toward the pole on the right of sunrise",
    "space": "a continuous area or expanse; outer space",
    "speak": "to say words aloud; to communicate verbally",
    "special": "better or greater than what is usual",
    "speed": "the rate at which someone or something moves",
    "spend": "to pay out money; to pass time",
    "spill": "to accidentally cause liquid to flow over the edge",
    "stand": "to be in an upright position on one's feet",
    "start": "to begin; the point at which something begins",
    "state": "a condition; a country or its government",
    "stay": "to remain in a place; to continue to be",
    "still": "not moving; up to and including the present time",
    "stop": "to cease moving or operating",
    "story": "an account of events; a level of a building",
    "strong": "having great power, strength, or force",
    "study": "to devote time to learning about a subject",
    "subject": "a topic; a person or thing being discussed",
    "success": "the accomplishment of a desired aim",
    "suggest": "to put forward for consideration",
    "support": "to bear the weight of; to help or encourage",
    "sure": "completely confident; certain",
    "system": "a set of connected things forming a complex whole",
    "take": "to reach out and hold; to remove or steal",
    "talk": "to speak in order to give or exchange information",
    "teach": "to instruct someone; to cause to learn",
    "tell": "to communicate information to someone",
    "than": "introducing the second element in a comparison",
    "that": "used to identify a specific person or thing",
    "the": "denoting one or more people or things already mentioned",
    "their": "belonging to or associated with people previously mentioned",
    "them": "used to refer to two or more people previously mentioned",
    "then": "at that time; after that",
    "there": "in, at, or to that place",
    "they": "used to refer to two or more people or things",
    "thing": "an object that one need not or cannot specify",
    "think": "to have a particular opinion or belief",
    "this": "used to identify a specific person or thing close at hand",
    "though": "despite the fact that; however",
    "thought": "an idea or opinion produced by thinking",
    "through": "moving in one side and out of the other",
    "time": "the indefinite continued progress of existence",
    "today": "on or in the course of this present day",
    "together": "with or in proximity to another person or people",
    "tomorrow": "the day after today",
    "toward": "in the direction of",
    "town": "a built-up area larger than a village",
    "travel": "to go from one place to another",
    "true": "in accordance with fact or reality",
    "trust": "firm belief in the reliability of someone",
    "truth": "the quality of being in accordance with fact",
    "turn": "to move in a circular direction; a time to do something",
    "type": "a category of things; to write using a keyboard",
    "under": "extending or directly below something",
    "understand": "to be aware of the meaning of",
    "until": "up to the point in time when",
    "upon": "more formal word for on",
    "use": "to take or consume for a purpose",
    "usually": "under normal conditions; generally",
    "value": "the importance or worth of something",
    "view": "the ability to see something; an opinion",
    "visit": "to go to see and spend time with someone",
    "voice": "the sound produced in a person's throat when speaking",
    "wait": "to stay where one is until something happens",
    "walk": "to move at a regular pace by lifting the feet",
    "want": "to have a desire to possess or do something",
    "watch": "to look at attentively; a small timepiece worn on the wrist",
    "water": "a colorless liquid which forms seas, rivers, and rain",
    "week": "a period of seven days",
    "well": "in a good or satisfactory way; healthy",
    "west": "the direction in which the sun sets",
    "what": "asking for information about something",
    "when": "at what time; at the time that",
    "where": "in or to what place",
    "whether": "expressing a doubt or choice between alternatives",
    "which": "asking for information about a choice",
    "while": "during the time that; although",
    "white": "the color of snow or milk",
    "whole": "all of; complete; in one piece",
    "wide": "of great or more than average width",
    "will": "expressing the future tense; a desire or intention",
    "within": "inside; not beyond",
    "without": "not having or showing; in the absence of",
    "word": "a single unit of language",
    "work": "activity involving effort done to achieve a purpose",
    "world": "the earth with all its countries and people",
    "worry": "to feel anxious or troubled",
    "would": "past tense of will; used to express possibility",
    "write": "to mark letters or words on a surface",
    "wrong": "not correct or true; unjust",
    "year": "a period of 365 days",
    "yet": "up until now or then; but at the same time",
    "young": "having lived or existed for only a short time",
    "your": "belonging to or associated with the person addressed",
}


def get_definition(word: str) -> str:
    """Return the definition of *word*, or an empty string if not found."""
    return DEFINITIONS.get(word.lower().strip(), "")
